### ISSUE TITLE
print(Filter) exhausts the iterator.

### ISSUE THREAD

**Issue by maxnoe** [seperman/bad-ideas#1]
I now it's called **bad** ideas, but nevertheless, this is kind of surprising

```python

>>> f = filtererd(lambda x: x % 2 == 0, range(10))
>>> print(f)
[0, 2, 4, 6, 8]
>>> for a in f:
>>>     print(a)

```

**Comment by seperman** [comment]
Haha, good point. Thanks for reporting @MaxNoe

**Comment by maxnoe** [comment]
I experimented a bit with `itertools.tee`  but couldn't get it to work, as I can  not overwrite the `__dict__` and `__class__` attributes.

**Comment by seperman** [comment]
I was gonna play with `__iter__` to make it work. Will keep you posted.

**Comment by seperman** [comment]
@MaxNoe This issue is fixed. The solution is not really a "bad idea" anymore though.

**Comment by maxnoe** [comment]
Just for the record :-D I never intended to use it. It just came to my mind watching your talk. Great talk, btw.

**Comment by seperman** [comment]
Haha I see! Thanks @MaxNoe 
I will put back the original code when I have a chance then. And keep some notes about iterators exhaustion.
